# Generated by Django 3.1.1 on 2020-09-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20200913_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_id',
        ),
    ]
